spring:
  application:
    name: tukuntech-api-gateway

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        # ========= RUTAS DE OPENAPI (DOCS) =========
        - id: auth-openapi
          uri: lb://TUKUNTECH-MS-IAM
          predicates:
            - Path=/api/v1/auth/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/auth/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: profiles-openapi
          uri: lb://TUKUNTECH-MS-PROFILES
          predicates:
            - Path=/api/v1/profiles/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/profiles/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: support-openapi
          uri: lb://TUKUNTECH-MS-SUPPORT
          predicates:
            - Path=/api/v1/support/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/support/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: reports-openapi
          uri: lb://TUKUNTECH-MS-REPORT
          predicates:
            - Path=/api/v1/reports/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/reports/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: monitoring-openapi
          uri: lb://TUKUNTECH-MS-MONITORING
          predicates:
            - Path=/api/v1/monitoring/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/monitoring/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        - id: care-openapi
          uri: lb://TUKUNTECH-MS-CARE
          predicates:
            - Path=/api/v1/care/v3/api-docs/**
          filters:
            - RewritePath=/api/v1/care/v3/api-docs(?<segment>/?.*), /api/v1/v3/api-docs${segment}

        # ========= RUTAS DE NEGOCIO =========
        - id: auth
          uri: lb://TUKUNTECH-MS-IAM
          predicates:
            - Path=/api/v1/auth/**

        - id: profiles
          uri: lb://TUKUNTECH-MS-PROFILES
          predicates:
            - Path=/api/v1/profiles/**

        - id: support
          uri: lb://TUKUNTECH-MS-SUPPORT
          predicates:
            - Path=/api/v1/support/**

        - id: reports
          uri: lb://TUKUNTECH-MS-REPORT
          predicates:
            - Path=/api/v1/reports/**

        - id: monitoring
          uri: lb://TUKUNTECH-MS-MONITORING
          predicates:
            - Path=/api/v1/monitoring/**

        - id: care
          uri: lb://TUKUNTECH-MS-CARE
          predicates:
            - Path=/api/v1/care/**

server:
  port: 8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /api/v1/swagger-ui.html
    urls:
      - name: auth-service
        url: /api/v1/auth/v3/api-docs
      - name: profiles-service
        url: /api/v1/profiles/v3/api-docs
      - name: support-service
        url: /api/v1/support/v3/api-docs
      - name: reports-service
        url: /api/v1/reports/v3/api-docs
      - name: monitoring-service
        url: /api/v1/monitoring/v3/api-docs
      - name: care-service
        url: /api/v1/care/v3/api-docs

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
