spring:
  application:
    name: tukuntech-api-gateway

  cloud:
    compatibility-verifier:
      enabled: false

    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - http://localhost:4200
            allowedMethods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            exposedHeaders: "*"
            allowCredentials: true

      default-filters:
        - RemoveRequestHeader=Cookie
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_FIRST

      routes:
        - id: auth
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/auth/**

        - id: profiles
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/profiles/**

        - id: monitoring
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/monitoring/**

        - id: care
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/care/**

        - id: reports
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/reports/**

        - id: support
          uri: http://localhost:8087
          predicates:
            - Path=/api/v1/support/**

        - id: swagger-docs
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/v3/api-docs/**

        - id: swagger-ui
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/swagger-ui/**,/api/v1/swagger-ui.html

        - id: actuator-v1
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/actuator/**

        - id: actuator-root
          uri: http://localhost:8080
          predicates:
            - Path=/actuator/**

        - id: monolith-fallback
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**

server:
  port: 8081
